#!/bin/bash

# VARIABLES
verbose_mode=false
work=false

print_help() {
	# Display help
	echo "Clone a git repository as bare to use git worktree feature"
	echo
	echo "Syntax: gcb [-h|v|w]"
	echo "options:"
	echo "h     Print Help."
	echo "v     Verbose mode."
	echo "w     Use work git config"
	echo "u     ssh git url"
	echo
	echo "Example for work repo"
	echo "gcb -u git:workOrganization/work-repo.git -w"
	echo
	echo "Example for personal repo"
	echo "gcb -u git:tostca/.dotfiles.git"
}

has_argument() {
	[[ ("$1" == *=* && -n ${1#*=}) || (! -z "$2" && "$2" != -*) ]]
}

extract_argument() {
	echo "${2:-${1#*=}}"
}

# Function to handle options and arguments
handle_options() {
	while [ $# -gt 0 ]; do
		case $1 in
		-h | --help)
			print_help
			exit 0
			;;
		-v | --verbose)
			verbose_mode=true
			;;
		-w | --work)
			work=true
			;;
		-u | --url*)
			if ! has_argument $@; then
				echo "Url not specified." >&2
				print_help
				exit 1
			fi

			ssh_url=$(extract_argument $@)

			shift
			;;
		*)
			echo "Invalid option: $1" >&2
			print_help
			exit 1
			;;
		esac
		shift
	done
}

# Main script execution
handle_options "$@"

# Perform the desired actions based on the provided flags and arguments
if [ "$verbose_mode" = true ]; then
	echo "Verbose mode enabled."
fi

if [ "$work" = true ]; then
	work_ssh_url=$(echo $ssh_url | sed "s/git@github.com/workgit/")
	repo_name=$(basename $work_ssh_url .git)
	echo "repo_name: $repo_name"

	if [ "$verbose_mode" = true ]; then
		echo "Start cloning: $work_ssh_url."
		echo "repo_name: $repo_name"
	fi

	git clone --bare $work_ssh_url $repo_name
	cd $repo_name

	if [ "$verbose_mode" = true ]; then
		echo "Set git remote.origin.fetch $work_ssh_url."
	fi

	git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
else
	repo_name=$(basename $ssh_url .git)
	echo "ssh url: $ssh_url"
	echo "repo_name: $repo_name"

	if [ "$verbose_mode" = true ]; then
		echo "Start cloning: $ssh_url."
		echo "repo_name: $repo_name"
	fi

	git clone --bare $ssh_url $repo_name
	cd $repo_name

	if [ "$verbose_mode" = true ]; then
		echo "Set git remote.origin.fetch $work_ssh_url."
	fi

	git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
fi

if [ "$verbose_mode" = true ]; then
	echo "Finished"
fi
